% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Life Expectancy Trends (2000-2015)},
  pdfauthor={Marissa Alfieri, Jenny Zheng, Letitia Caspersen},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Life Expectancy Trends (2000-2015)}
\author{Marissa Alfieri, Jenny Zheng, Letitia Caspersen}
\date{2025-11-04}

\begin{document}
\maketitle

\subsection{Introduction}\label{introduction}

Life expectancy says a lot about how people live and the conditions they
face around the world. In this project, we wanted to look at how life
expectancy differs across continents and how it changes over time. We
started by checking whether continents already had different average
life expectancies in the year 2000. That way we could get a baseline
snapshot of global inequality. Then, we tested whether those differences
changed between 2000 and 2015 to see if countries have been getting
closer together or if the gap has stayed the same.

The main goal is to understand whether the differences in life
expectancy reflect ongoing global inequality or improvements that are
happening unevenly across regions.

The data come from Kaggle's Life Expectancy 2000--2015 dataset
(\url{https://www.kaggle.com/datasets/vrec99/life-expectancy-2000-2015}),
which combines information from the World Health Organization, World
Bank, and the United Nations. It includes 119 countries across 15 years,
with variables like GDP per capita, CO₂ emissions, health expenditure,
and internet access.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{=} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"Life\_Expectancy.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Section 1 -- Comparing Continents in
2000}\label{section-1-comparing-continents-in-2000}

We wanted to start by establishing a baseline for global inequality in
life expectancy. To see whether people in some continents were living
longer than others at the start of the 21st century.

Our hypotheses were:

\begin{quote}
\(H_0: \text{The distributions of life expectancy are the same across all continents.}\)

\(H_a: \text{At least one continent differs.}\)
\end{quote}

\subsubsection{\texorpdfstring{\textbf{Checking The
Assumptions}}{Checking The Assumptions}}\label{checking-the-assumptions}

We planned to test this using a one-way ANOVA, so we first checked
whether the assumptions of normality and equal variances were met.

\paragraph{\texorpdfstring{\textbf{1.
Normality}}{1. Normality}}\label{normality}

Normality is important because ANOVA assumes that residuals within each
group are normally distributed.

\[
\ H_0: \text{The life expectancy values within each continent are normally distributed.}
\]

\[
\ H_a: \text{The life expectancy values within at least one continent deviate from normality.}
\]

For normality, we visually inspected histograms of life expectancy for
each continent.

\pandocbounded{\includegraphics[keepaspectratio]{Project_files/figure-latex/unnamed-chunk-1-1.pdf}}

Visual inspection of the histograms suggested that the distributions
were varied, with some having approximately bell shaped curves, some
with unique distributions, and some skewed. To confirm normality
statistically, we used a Monte Carlo Anderson--Darling test.

This test measures how far the observed data deviates from what would be
expected under a normal distribution with the same mean and standard
deviation. Comparing our observed statistic to this simulated one let us
estimate the p-value and decide whether the normality assumption held.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123123}\NormalTok{)}
\NormalTok{nmc }\OtherTok{=} \DecValTok{10000}
\NormalTok{n }\OtherTok{=} \FunctionTok{length}\NormalTok{(x)}
\NormalTok{mc\_ad }\OtherTok{=} \FunctionTok{c}\NormalTok{()}

\CommentTok{\# observed statistic}
\NormalTok{x\_sorted }\OtherTok{=} \FunctionTok{sort}\NormalTok{(x)}
\NormalTok{F\_emp }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n) }\SpecialCharTok{/}\NormalTok{ (n}\SpecialCharTok{+}\DecValTok{1}\NormalTok{)}
\NormalTok{F\_null }\OtherTok{=} \FunctionTok{pnorm}\NormalTok{(x\_sorted, }\FunctionTok{mean}\NormalTok{(x\_sorted), }\FunctionTok{sd}\NormalTok{(x\_sorted)) }
\NormalTok{AD\_obs }\OtherTok{=} \FunctionTok{sum}\NormalTok{(((}\FunctionTok{abs}\NormalTok{(F\_emp }\SpecialCharTok{{-}}\NormalTok{ F\_null))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ (F\_emp }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ F\_emp)))}

\CommentTok{\# simulated normality}
\ControlFlowTok{for}\NormalTok{(k }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{nmc)\{}
\NormalTok{  smc }\OtherTok{=} \FunctionTok{sort}\NormalTok{(}\FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\NormalTok{  F\_emp\_mc }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n)}\SpecialCharTok{/}\NormalTok{(n}\SpecialCharTok{+}\DecValTok{1}\NormalTok{)}
\NormalTok{  F\_null\_mc }\OtherTok{=} \FunctionTok{pnorm}\NormalTok{(smc, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{)}
\NormalTok{  mc\_ad }\OtherTok{=} \FunctionTok{c}\NormalTok{(mc\_ad, }\FunctionTok{sum}\NormalTok{((F\_emp\_mc }\SpecialCharTok{{-}}\NormalTok{ F\_null\_mc)}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{/}\NormalTok{ (F\_emp\_mc }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ F\_emp\_mc))))}
\NormalTok{  \}}

\NormalTok{alpha }\OtherTok{=} \FloatTok{0.10}
\NormalTok{ad\_crit }\OtherTok{=} \FunctionTok{quantile}\NormalTok{(mc\_ad, }\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha)}
\NormalTok{emp\_pval }\OtherTok{=} \FunctionTok{mean}\NormalTok{(mc\_ad }\SpecialCharTok{\textgreater{}=}\NormalTok{ AD\_obs)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Anderson–Darling Critical Value: 2
\end{verbatim}

\begin{verbatim}
## Empirical P-Value: 0
\end{verbatim}

The Anderson--Darling test gave an empirical p-value of 0.0004, which is
below the alpha level of 0.10. This means we reject the null hypothesis
of normality. So, the life expectancy data for 2000 aren't normally
distributed. This makes sense because some continents have much higher
averages while others are lower, so the data are naturally skewed
instead of bell-shaped. Before deciding how to move forward, we also
wanted to check whether the variability between groups was similar,
because large differences in spread can also affect ANOVA results.

\paragraph{\texorpdfstring{\textbf{2. Testing Equal
Variances}}{2. Testing Equal Variances}}\label{testing-equal-variances}

Equal variances (homoscedasticity) matter because ANOVA assumes that all
groups have about the same level of variability. If one continent's life
expectancy values are way more spread out than another's, the results
can be misleading.

\[
\ H_0: \text{The variances of life expectancy among continents are equal.}
\]

\[
\ H_a: \text{At least one group’s variance differs.}
\]

We used the Bartlett statistic, which tests whether the variances of
life expectancy across groups (\(j\)) are equal. It compares each
group's sample variance (\(s_j^2\)) to the pooled variance (\(s_p^2\))
that would be expected if all groups had the same variability. The
Bartlett statistic (\(B_{\text{stat}}\)) is computed as:

\[
Bstat = \frac{v * ln(s_p^2) - (\sum_{j=1}^{g}v_j * ln(s_j^2) )}{1 + \frac{1}{3(g-1)}* [(\sum_{j=1}^{g} \frac{1}{v_j})- \frac{1}{v}]}
\]

First, we split the dataset by continent so that we could calculate each
group's mean, variance, and sample size:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xs }\OtherTok{=} \FunctionTok{split}\NormalTok{(x, data\_2000}\SpecialCharTok{$}\NormalTok{Continent)}
\NormalTok{xbarj }\OtherTok{=} \FunctionTok{sapply}\NormalTok{(xs, mean)}
\NormalTok{s2j }\OtherTok{=} \FunctionTok{sapply}\NormalTok{(xs, var)}
\NormalTok{nj}\OtherTok{=} \FunctionTok{sapply}\NormalTok{ (xs, length)}
\end{Highlighting}
\end{Shaded}

Each continent's variance (\(s_j^2\)) represents how spread out its life
expectancy values are. Then we calculated each group's degrees of
freedom (\(v_j=n_j-1\)) and counted the number of groups (\(g\)):

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{vj}\OtherTok{=}\NormalTok{ nj}\DecValTok{{-}1}
\NormalTok{g}\OtherTok{=} \FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(data\_2000}\SpecialCharTok{$}\NormalTok{Continent))}
\end{Highlighting}
\end{Shaded}

Next, we computed the pooled variance, which combines the group
variances into a single weighted value based on their degrees of
freedom: \[
s_p^2=\frac{\sum_{j=1}^{g}v_js_j^2}{\sum_{j=1}^{g}v_j}
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sp2 }\OtherTok{=} \FunctionTok{sum}\NormalTok{(vj }\SpecialCharTok{*}\NormalTok{ s2j)}\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(vj)}
\end{Highlighting}
\end{Shaded}

After defining the components for each continent (sample variance
\(s_j^2\), degrees of freedom \(v_j\), and the number of groups \(g\)),
we computed the Bartlett statistic:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bastat }\OtherTok{=}\NormalTok{ ((}\FunctionTok{sum}\NormalTok{(vj) }\SpecialCharTok{*} \FunctionTok{log}\NormalTok{(sp2)) }\SpecialCharTok{{-}} \FunctionTok{sum}\NormalTok{(vj }\SpecialCharTok{*} \FunctionTok{log}\NormalTok{(s2j)))}\SpecialCharTok{/}
\NormalTok{  (}\DecValTok{1}\SpecialCharTok{+} \DecValTok{1}\SpecialCharTok{/}\NormalTok{(}\DecValTok{3}\SpecialCharTok{*}\NormalTok{(g}\DecValTok{{-}1}\NormalTok{))}\SpecialCharTok{*}\NormalTok{ (}\FunctionTok{sum}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\NormalTok{vj)}\SpecialCharTok{{-}} \DecValTok{1}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(vj)))}

\NormalTok{pval }\OtherTok{=} \FunctionTok{pchisq}\NormalTok{(bastat, g}\DecValTok{{-}1}\NormalTok{, }\AttributeTok{lower.tail=}\NormalTok{ F)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Bartlett’s Test Statistic: 26.5106
\end{verbatim}

\begin{verbatim}
## Bartlett’s Test P-Value: 7.102463e-05
\end{verbatim}

The Bartlett's test returned a test statistic of 26.51 and a p-value of
0.0001, which is below the alpha level of 0.10. This means we reject the
null hypothesis and conclude that the variances of life expectancy are
not equal across continents. So, the spread of life expectancy values
differs depending on the region.

\subsubsection{\texorpdfstring{\textbf{Kruskal--Wallis Test: Comparing
Continents in
2000}}{Kruskal--Wallis Test: Comparing Continents in 2000}}\label{kruskalwallis-test-comparing-continents-in-2000}

Since both assumptions, normality and equal variances, were violated, we
used the Kruskal--Wallis test instead of a standard one-way ANOVA.
Instead of comparing the means of the groups, it compares the ranks of
the data to see whether the distributions differ across continents.

The hypotheses are:

\[
\ H_0: \text{The distributions of life expectancy are the same across all continents.} 
\]

\[
\ H_a: \text{At least one continent differs.}
\]

We used the Kruskal--Wallis statistic, which tests whether the
distributions of life expectancy across groups (\(j\)) are the same. It
ranks all observations together, then compares the average rank within
each group (\(\bar{R}_j\)) to the overall mean rank (\(\bar{R}\)). If
the group ranks differ a lot, it suggests that at least one continent's
distribution is different. The Kruskal--Wallis statistic (\(H\)) is
computed as:

\[
H = \frac{12}{N(N + 1)} \sum_{j=1}^{g} n_j (\bar{R}_j - \bar{R})^2
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{R\_all }\OtherTok{=} \FunctionTok{rank}\NormalTok{(}\FunctionTok{unlist}\NormalTok{(xs))}
\NormalTok{Rj }\OtherTok{=} \FunctionTok{split}\NormalTok{(R\_all, }\FunctionTok{rep}\NormalTok{(}\FunctionTok{names}\NormalTok{(xs), }\AttributeTok{times =} \FunctionTok{sapply}\NormalTok{(xs, length)))}
\NormalTok{nj }\OtherTok{=} \FunctionTok{sapply}\NormalTok{(Rj, length)}
\NormalTok{N }\OtherTok{=} \FunctionTok{sum}\NormalTok{(nj)}
\NormalTok{g }\OtherTok{=} \FunctionTok{length}\NormalTok{(Rj)}
\NormalTok{Rbar\_j }\OtherTok{=} \FunctionTok{sapply}\NormalTok{(Rj, mean)}
\NormalTok{Rbar }\OtherTok{=}\NormalTok{ (N }\SpecialCharTok{+} \DecValTok{1}\NormalTok{) }\SpecialCharTok{/} \DecValTok{2}

\NormalTok{H\_stat }\OtherTok{=}\NormalTok{ (}\DecValTok{12} \SpecialCharTok{/}\NormalTok{ (N }\SpecialCharTok{*}\NormalTok{ (N }\SpecialCharTok{+} \DecValTok{1}\NormalTok{))) }\SpecialCharTok{*} \FunctionTok{sum}\NormalTok{(nj }\SpecialCharTok{*}\NormalTok{ (Rbar\_j }\SpecialCharTok{{-}}\NormalTok{ Rbar)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{pval\_kw }\OtherTok{=} \FunctionTok{pchisq}\NormalTok{(H\_stat, g }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Kruskal–Wallis H Statistic: 65.0293
\end{verbatim}

\begin{verbatim}
## P-Value: 1.105162e-12
\end{verbatim}

The Kruskal--Wallis test returned an \(H\) statistic of 65.03 with a
p-value of 1.10 \textbf{×} 10⁻¹², which is below the alpha level of
0.10. This means we reject the null hypothesis and conclude that life
expectancy distributions differ significantly across continents in the
year 2000.

Therefore, there was clear inequality in life expectancy at the start of
the 21st century, some regions were already living much longer on
average than others. This result confirms that the gap in global health
outcomes was large even before major medical and economic developments
of the following decades.

\subsection{Section 2 -- Comparing Continents in from
2000-2015}\label{section-2-comparing-continents-in-from-2000-2015}

After finding that life expectancy differed across continents in 2000,
we wanted to see whether those differences changed over time. Did the
gap between regions decrease or have some continents continued to fall
behind? To figure that out, we looked at how the average life expectancy
changed from 2000 to 2015.

Our hypotheses were:

\[
H_0: \mu_{\text{2000}} = \mu_{\text{2001}} = \mu_{\text{2002}} = \dots = \mu_{\text{2015}} \\H_a: \text{At least one mean differs.}
\]

\subsubsection{\texorpdfstring{\textbf{Checking The
Assumptions}}{Checking The Assumptions}}\label{checking-the-assumptions-1}

We planned to test this using a repeated-measures ANOVA, so we first
checked whether the assumptions of normality, sphericity, and
independence were met.

\paragraph{\texorpdfstring{\textbf{1.
Normality}}{1. Normality}}\label{normality-1}

Normality is important because repeated-measures ANOVA assumes that the
residuals (or differences between time points) are roughly normally
distributed.

\[
\ H_0: \text{The life expectancy values across years are normally distributed.} \\
\ H_a: \text{The life expectancy values deviate from normality.}
\] To test this, we used the Kolmogorov--Smirnov test, which compares
the sample's cumulative distribution to a normal distribution with the
same mean and standard deviation.

The KS statistic (\(D\)) is computed as:

\[
D = \max \left| F_{\text{emp}}(x) - F_{\text{null}}(x) \right|
\]

In R, it was calculated as:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{=}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{Life.Expectancy}
\NormalTok{x\_sorted }\OtherTok{=} \FunctionTok{sort}\NormalTok{(x)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123123}\NormalTok{)}
\NormalTok{nmc }\OtherTok{=} \DecValTok{10000}
\NormalTok{n }\OtherTok{=} \FunctionTok{length}\NormalTok{(x\_sorted)}

\CommentTok{\# observed statistic}
\NormalTok{F\_emp }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n) }\SpecialCharTok{/}\NormalTok{ (n}\SpecialCharTok{+}\DecValTok{1}\NormalTok{)}
\NormalTok{F\_null }\OtherTok{=} \FunctionTok{pnorm}\NormalTok{(x\_sorted, }\FunctionTok{mean}\NormalTok{(x\_sorted), }\FunctionTok{sd}\NormalTok{(x\_sorted)) }
\NormalTok{KS\_obs }\OtherTok{=} \FunctionTok{max}\NormalTok{(}\FunctionTok{abs}\NormalTok{(F\_emp }\SpecialCharTok{{-}}\NormalTok{ F\_null))}

\CommentTok{\# simulated normality}
\NormalTok{KS\_mc }\OtherTok{=} \FunctionTok{c}\NormalTok{()}
\ControlFlowTok{for}\NormalTok{(k }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{nmc)\{}
\NormalTok{  smc }\OtherTok{=} \FunctionTok{sort}\NormalTok{(}\FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\NormalTok{  F\_emp\_mc }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n) }\SpecialCharTok{/}\NormalTok{ (n}\SpecialCharTok{+}\DecValTok{1}\NormalTok{)}
\NormalTok{  F\_null\_mc }\OtherTok{=} \FunctionTok{pnorm}\NormalTok{(smc, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{)}
\NormalTok{  KS\_mc }\OtherTok{=} \FunctionTok{c}\NormalTok{(KS\_mc, }\FunctionTok{max}\NormalTok{(}\FunctionTok{abs}\NormalTok{(F\_emp\_mc }\SpecialCharTok{{-}}\NormalTok{ F\_null\_mc)))}
\NormalTok{  \}}

\NormalTok{alpha }\OtherTok{=} \FloatTok{0.10}
\NormalTok{KS\_crit }\OtherTok{=} \FunctionTok{quantile}\NormalTok{(KS\_mc, }\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha)}
\NormalTok{emp\_pval }\OtherTok{=} \FunctionTok{mean}\NormalTok{(KS\_mc }\SpecialCharTok{\textgreater{}=}\NormalTok{ KS\_obs)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Kolmogorov–Smirnov Critical Value: 0.02790051
\end{verbatim}

\begin{verbatim}
## Empirical P-Value: 0
\end{verbatim}

The Kolmogorov--Smirnov test gave a critical value of 0.0279 and an
empirical p-value of 0, which is below the alpha level of 0.10. This
means we reject the null hypothesis of normality. So, the life
expectancy values across years aren't normally distributed. Before
deciding how to move forward, we also wanted to check the assumption of
sphericity, which deals with the relationships between repeated
measurements over time.

\paragraph{\texorpdfstring{\textbf{2.
Sphericity}}{2. Sphericity}}\label{sphericity}

Sphericity is the repeated-measures version of equal variances. It
assumes that the variances of the differences between every pair of
years are roughly equal.

\[
\ H_0: \text{The variances of the differences between all pairs of years are equal.} \\
\ H_a: \text{At least one pair of years differs in variance of differences.}
\]

We computed Mauchly's test to evaluate the sphericity assumption. This
test measures whether the covariance matrix of repeated measures is
close to spherical.

The Mauchly statistic (\(W\)) is calculated as: \[
W = \frac{|\Sigma|}{\left( \frac{\text{tr}(\Sigma)}{k} \right)^k}
\]

where \(|\Sigma|\) is the determinant of the covariance matrix and
\(\text{tr}(\Sigma)\) is its trace.

The test statistic (\(M_{\text{stat}}\) ) is then computed as:

\[
M_{\text{stat}} = -(n - 1) \ln(W)
\]

is then computed as:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{k }\OtherTok{=} \FunctionTok{ncol}\NormalTok{(x)}
\NormalTok{n }\OtherTok{=} \FunctionTok{nrow}\NormalTok{(x)}
\NormalTok{c }\OtherTok{=} \FunctionTok{cov}\NormalTok{(x)}
\NormalTok{tr }\OtherTok{=} \FunctionTok{sum}\NormalTok{(}\FunctionTok{diag}\NormalTok{(c))}
\NormalTok{det }\OtherTok{=} \FunctionTok{det}\NormalTok{(c)}

\NormalTok{W }\OtherTok{=}\NormalTok{ det }\SpecialCharTok{/}\NormalTok{ ((tr }\SpecialCharTok{/}\NormalTok{ k)}\SpecialCharTok{\^{}}\NormalTok{k)}
\NormalTok{Mstat }\OtherTok{=} \SpecialCharTok{{-}}\NormalTok{(n}\DecValTok{{-}1}\NormalTok{) }\SpecialCharTok{*} \FunctionTok{log}\NormalTok{(W) }
\NormalTok{df }\OtherTok{=}\NormalTok{ (k}\SpecialCharTok{*}\NormalTok{(k}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{/}\DecValTok{2}\NormalTok{)}
\NormalTok{Mcrit }\OtherTok{=} \FunctionTok{qchisq}\NormalTok{(}\DecValTok{1}\FloatTok{{-}0.10}\NormalTok{, df)}
\NormalTok{Mpval }\OtherTok{=} \FunctionTok{pchisq}\NormalTok{(Mstat, df,}\AttributeTok{lower.tail =}\NormalTok{ F)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Mauchly's Test Statistic: 2119.985
\end{verbatim}

\begin{verbatim}
## Mauchly's Test P-Value: 0
\end{verbatim}

\end{document}
